# Generated by Django 6.0.4 on 2026-05-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movement',
            options={'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos (Kárdex)'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stock'},
        ),
    ]
