# Generated by Django 6.0.4 on 2026-06-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_alter_area_options_alter_area_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
    ]
