# Generated by Django 6.0.4 on 2026-05-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('guest', 'Guest'), ('almacen', 'Almacen'), ('inventario', 'Inventario'), ('cliente', 'Cliente'), ('proveedor', 'Proveedor')], default='user', max_length=20),
        ),
    ]
