# Generated by Django 6.0.4 on 2026-05-27 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('icono', models.CharField(blank=True, default='', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RolModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('guest', 'Guest'), ('almacen', 'Almacen'), ('inventario', 'Inventario'), ('cliente', 'Cliente'), ('proveedor', 'Proveedor')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_modulos', to='accounts.modulo')),
            ],
            options={
                'unique_together': {('rol', 'modulo')},
            },
        ),
    ]
