# Generated by Django 6.0.4 on 2026-06-21 20:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_modulo_rolmodulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rolmodulo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolmodulo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rolmodulo',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rol_modulos', to='accounts.modulo'),
        ),
    ]
