# Generated by Django 6.0.4 on 2026-06-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_modulo_created_modulo_updated_rolmodulo_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='grupo',
            field=models.CharField(choices=[('principal', 'Principal'), ('administracion', 'Administración')], default='principal', max_length=20),
        ),
    ]
