# Generated by Django 6.0.4 on 2026-05-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Entrega (PECOSA)', 'verbose_name_plural': 'Entregas (PECOSA)'},
        ),
        migrations.AlterModelOptions(
            name='deliverydetail',
            options={'verbose_name': 'Detalle de entrega', 'verbose_name_plural': 'Detalles de entrega'},
        ),
    ]
