# Generated by Django 6.0.4 on 2026-05-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0002_alter_delivery_options_alter_deliverydetail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Entrega', 'verbose_name_plural': 'Entregas'},
        ),
    ]
