# Generated by Django 6.0.4 on 2026-05-06 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0003_alter_delivery_options'),
        ('productos', '0003_alter_category_created_alter_category_description_and_more'),
        ('solicitudes', '0004_alter_requestdetail_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.request', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('DELIVERED', 'Entregado'), ('DISCONTENT', 'Disconforme')], default='PENDING', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='entregas.delivery', verbose_name='Entrega'),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='quantity_delivered',
            field=models.IntegerField(verbose_name='Cantidad Entregada'),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
    ]
