# Generated by Django 6.0.4 on 2026-05-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='unitmeasure',
            options={'verbose_name': 'Unidad de medida', 'verbose_name_plural': 'Unidades de medida'},
        ),
    ]
