# Generated by Django 6.0.4 on 2026-05-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AlterModelOptions(
            name='requestdetail',
            options={'verbose_name': 'Detalle de solicitud', 'verbose_name_plural': 'Detalles de solicitud'},
        ),
    ]
