# Generated by Django 6.0.4 on 2026-05-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_category_created_alter_category_description_and_more'),
        ('solicitudes', '0003_alter_request_area_alter_request_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestdetail',
            options={'verbose_name': 'Detalle de solicitud', 'verbose_name_plural': 'Detalles'},
        ),
        migrations.AlterField(
            model_name='requestdetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='requestdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='requestdetail',
            name='quantity_attended',
            field=models.IntegerField(default=0, verbose_name='Cantidad Atendida'),
        ),
        migrations.AlterField(
            model_name='requestdetail',
            name='quantity_requested',
            field=models.IntegerField(verbose_name='Cantidad Solicitada'),
        ),
        migrations.AlterField(
            model_name='requestdetail',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='solicitudes.request', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='requestdetail',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
    ]
