# Generated by Django 6.0.4 on 2026-05-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reception',
            options={'verbose_name': 'Recepción', 'verbose_name_plural': 'Recepciones'},
        ),
        migrations.AlterModelOptions(
            name='receptiondetail',
            options={'verbose_name': 'Detalle de recepción', 'verbose_name_plural': 'Detalles de recepción'},
        ),
        migrations.AlterField(
            model_name='reception',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
