# Generated by Django 6.0.4 on 2026-05-06 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_purchaseorder_code_alter_purchaseorder_created_and_more'),
        ('productos', '0003_alter_category_created_alter_category_description_and_more'),
        ('recepcion', '0002_alter_reception_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='ordenes.purchaseorder', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completada'), ('INCOMPLETE', 'Incompleta'), ('INCIDENT', 'Con incidencia')], default='INCOMPLETE', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='receptiondetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='receptiondetail',
            name='has_incident',
            field=models.BooleanField(default=False, verbose_name='Con Incidencia'),
        ),
        migrations.AlterField(
            model_name='receptiondetail',
            name='incident_notes',
            field=models.TextField(blank=True, verbose_name='Notas de Incidencia'),
        ),
        migrations.AlterField(
            model_name='receptiondetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='receptiondetail',
            name='quantity_expected',
            field=models.IntegerField(verbose_name='Cantidad Esperada'),
        ),
        migrations.AlterField(
            model_name='receptiondetail',
            name='quantity_received',
            field=models.IntegerField(default=0, verbose_name='Cantidad Recibida'),
        ),
        migrations.AlterField(
            model_name='receptiondetail',
            name='reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='recepcion.reception', verbose_name='Recepción'),
        ),
        migrations.AlterField(
            model_name='receptiondetail',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
    ]
