# Generated by Django 6.0.4 on 2026-05-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'Orden de compra', 'verbose_name_plural': 'Órdenes de compra'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderdetail',
            options={'verbose_name': 'Detalle de orden', 'verbose_name_plural': 'Detalles de orden'},
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('APPROVED', 'Aprobada'), ('SENT', 'Enviada'), ('RECEIVED', 'Recibida'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=15),
        ),
    ]
