# Generated by Django 6.0.4 on 2026-05-06 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_purchaseorder_options_and_more'),
        ('productos', '0003_alter_category_created_alter_category_description_and_more'),
        ('proveedores', '0003_alter_supplier_address_alter_supplier_contact_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('APPROVED', 'Aprobada'), ('SENT', 'Enviada'), ('RECEIVED', 'Recibida'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.supplier', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ordenes.purchaseorder', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='quantity',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
    ]
